// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvSiXXCubiQPOd9DkkWNkOGs9Qk18tlMM',
    appId: '1:945574511714:web:44d4b72362427d1a4dbd3b',
    messagingSenderId: '945574511714',
    projectId: 'leohis',
    authDomain: 'leohis.firebaseapp.com',
    storageBucket: 'leohis.appspot.com',
    measurementId: 'G-49RS64C9BE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApiy2-LW7qCo_T7MmucTIyDQGhkqqSEWM',
    appId: '1:945574511714:android:c0df15ab86ec90e54dbd3b',
    messagingSenderId: '945574511714',
    projectId: 'leohis',
    storageBucket: 'leohis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCadQB-SH2vltK1uRhXO-Y4eHxsgYCy6wI',
    appId: '1:945574511714:ios:b619f104bf4846374dbd3b',
    messagingSenderId: '945574511714',
    projectId: 'leohis',
    storageBucket: 'leohis.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCadQB-SH2vltK1uRhXO-Y4eHxsgYCy6wI',
    appId: '1:945574511714:ios:a44ef37fb14fd8824dbd3b',
    messagingSenderId: '945574511714',
    projectId: 'leohis',
    storageBucket: 'leohis.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
